language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "Testing"
      script: 
        - npm test
    - stage: "Generate Testing Report"
      script: 
        - npm run test:coveralls
    - stage: "Building App"
      script: 
        - npm run build
    - stage: "Deploy App to Github Pages"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          branch: master
      